[project]
name = "stackin-python-sdk"
type = "library"
language = "python"

[source_host]
kind = "github"
repo = "stackin-io/stackin-python-sdk"

[release]
strategy = "semver"
changelog = "conventional"
