[project]
name = "stackin"
version = "0.1.0"
authors = [
  { name = "Fernando Celmer", email = "email@fernandocelmer.com" },
]
description = "🧾 SDK Python humano pro stackin-api (emitir/consultar/cancelar NF-e/NFS-e)."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "requests",
  "pydantic",
]

[tool.poetry]
name = "stackin"
version = "0.1.0"
description = "🧾 SDK Python humano pro stackin-api (emitir/consultar/cancelar NF-e/NFS-e)."
authors = ["Fernando Celmer <email@fernandocelmer.com>"]
readme = "README.md"
license = "MIT"
package-mode = true
packages = [{ include = "stackin" }]

[tool.poetry.dependencies]
python = ">=3.10.0"
requests = "^2.32.4"
pydantic = "^2.11.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
python-dotenv = "^1.0.1"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
