name: 📐 Contract

on:
  pull_request:
    branches: ["main", "master", "pypi"]
  push:
    branches: ["main", "master", "pypi"]
  workflow_dispatch:

jobs:
  contract:
    uses: stackin-io/stackin-sdk-template/.github/workflows/contract-conformance.yml@master
    with:
      lang: python
